//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSpot.Translations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.resx", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Reparented {
            get {
                return ResourceManager.GetString("Reparented", resourceCulture);
            }
        }
        
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        public static string ModifiedNumber {
            get {
                return ResourceManager.GetString("ModifiedNumber", resourceCulture);
            }
        }
        
        public static string ModifiedInName {
            get {
                return ResourceManager.GetString("ModifiedInName", resourceCulture);
            }
        }
        
        public static string ModifiedInNameNumber {
            get {
                return ResourceManager.GetString("ModifiedInNameNumber", resourceCulture);
            }
        }
        
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        public static string ParenNoneParen {
            get {
                return ResourceManager.GetString("ParenNoneParen", resourceCulture);
            }
        }
        
        public static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        public static string PaperSizeMmWidthHeight {
            get {
                return ResourceManager.GetString("PaperSizeMmWidthHeight", resourceCulture);
            }
        }
        
        public static string SetPageSizeAndOrientation {
            get {
                return ResourceManager.GetString("SetPageSizeAndOrientation", resourceCulture);
            }
        }
        
        public static string PhotosPerPage {
            get {
                return ResourceManager.GetString("PhotosPerPage", resourceCulture);
            }
        }
        
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        public static string PrintCutMarks {
            get {
                return ResourceManager.GetString("PrintCutMarks", resourceCulture);
            }
        }
        
        public static string PhotosLayout {
            get {
                return ResourceManager.GetString("PhotosLayout", resourceCulture);
            }
        }
        
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        public static string Scaled {
            get {
                return ResourceManager.GetString("Scaled", resourceCulture);
            }
        }
        
        public static string FullPageNoMargin {
            get {
                return ResourceManager.GetString("FullPageNoMargin", resourceCulture);
            }
        }
        
        public static string WhiteBorders {
            get {
                return ResourceManager.GetString("WhiteBorders", resourceCulture);
            }
        }
        
        public static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        public static string PhotosInfos {
            get {
                return ResourceManager.GetString("PhotosInfos", resourceCulture);
            }
        }
        
        public static string PrintFileName {
            get {
                return ResourceManager.GetString("PrintFileName", resourceCulture);
            }
        }
        
        public static string PrintPhotoDate {
            get {
                return ResourceManager.GetString("PrintPhotoDate", resourceCulture);
            }
        }
        
        public static string PrintPhotoTime {
            get {
                return ResourceManager.GetString("PrintPhotoTime", resourceCulture);
            }
        }
        
        public static string PrintPhotoTags {
            get {
                return ResourceManager.GetString("PrintPhotoTags", resourceCulture);
            }
        }
        
        public static string PrintPhotoComment {
            get {
                return ResourceManager.GetString("PrintPhotoComment", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string NoApplicationsAvailable {
            get {
                return ResourceManager.GetString("NoApplicationsAvailable", resourceCulture);
            }
        }
        
        public static string OriginalRaw {
            get {
                return ResourceManager.GetString("OriginalRaw", resourceCulture);
            }
        }
        
        public static string OriginalJpeg {
            get {
                return ResourceManager.GetString("OriginalJpeg", resourceCulture);
            }
        }
        
        public static string ImportedTags {
            get {
                return ResourceManager.GetString("ImportedTags", resourceCulture);
            }
        }
        
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        public static string UpdatingFSpotDatabase {
            get {
                return ResourceManager.GetString("UpdatingFSpotDatabase", resourceCulture);
            }
        }
        
        public static string WaitForGalleryDBToUpdate {
            get {
                return ResourceManager.GetString("WaitForGalleryDBToUpdate", resourceCulture);
            }
        }
        
        public static string AutoColor {
            get {
                return ResourceManager.GetString("AutoColor", resourceCulture);
            }
        }
        
        public static string AdjustColors {
            get {
                return ResourceManager.GetString("AdjustColors", resourceCulture);
            }
        }
        
        public static string Adjust {
            get {
                return ResourceManager.GetString("Adjust", resourceCulture);
            }
        }
        
        public static string FourByThreeBook {
            get {
                return ResourceManager.GetString("FourByThreeBook", resourceCulture);
            }
        }
        
        public static string FourBySixPostCard {
            get {
                return ResourceManager.GetString("FourBySixPostCard", resourceCulture);
            }
        }
        
        public static string FiveBySevenL2L {
            get {
                return ResourceManager.GetString("FiveBySevenL2L", resourceCulture);
            }
        }
        
        public static string EightByTen {
            get {
                return ResourceManager.GetString("EightByTen", resourceCulture);
            }
        }
        
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        public static string SelectTheAreaThatNeedsCropping {
            get {
                return ResourceManager.GetString("SelectTheAreaThatNeedsCropping", resourceCulture);
            }
        }
        
        public static string NoConstraint {
            get {
                return ResourceManager.GetString("NoConstraint", resourceCulture);
            }
        }
        
        public static string SameAsPhoto {
            get {
                return ResourceManager.GetString("SameAsPhoto", resourceCulture);
            }
        }
        
        public static string CustomRatios {
            get {
                return ResourceManager.GetString("CustomRatios", resourceCulture);
            }
        }
        
        public static string Desaturate {
            get {
                return ResourceManager.GetString("Desaturate", resourceCulture);
            }
        }
        
        public static string RedEyeReduction {
            get {
                return ResourceManager.GetString("RedEyeReduction", resourceCulture);
            }
        }
        
        public static string FixExclamation {
            get {
                return ResourceManager.GetString("FixExclamation", resourceCulture);
            }
        }
        
        public static string SelectTheEyesYouWishToFix {
            get {
                return ResourceManager.GetString("SelectTheEyesYouWishToFix", resourceCulture);
            }
        }
        
        public static string SepiaTone {
            get {
                return ResourceManager.GetString("SepiaTone", resourceCulture);
            }
        }
        
        public static string SoftFocus {
            get {
                return ResourceManager.GetString("SoftFocus", resourceCulture);
            }
        }
        
        public static string Straighten {
            get {
                return ResourceManager.GetString("Straighten", resourceCulture);
            }
        }
        
        public static string AndTerm {
            get {
                return ResourceManager.GetString("AndTerm", resourceCulture);
            }
        }
        
        public static string CommaSpace {
            get {
                return ResourceManager.GetString("CommaSpace", resourceCulture);
            }
        }
        
        public static string NotTagName {
            get {
                return ResourceManager.GetString("NotTagName", resourceCulture);
            }
        }
        
        public static string IncludePhotosTaggedTagName {
            get {
                return ResourceManager.GetString("IncludePhotosTaggedTagName", resourceCulture);
            }
        }
        
        public static string ExcludePhotosTaggedTagName {
            get {
                return ResourceManager.GetString("ExcludePhotosTaggedTagName", resourceCulture);
            }
        }
        
        public static string RemoveFromSearch {
            get {
                return ResourceManager.GetString("RemoveFromSearch", resourceCulture);
            }
        }
        
        public static string DragTagsHereToSearchForThem {
            get {
                return ResourceManager.GetString("DragTagsHereToSearchForThem", resourceCulture);
            }
        }
        
        public static string OrTerm {
            get {
                return ResourceManager.GetString("OrTerm", resourceCulture);
            }
        }
        
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        public static string FindColon {
            get {
                return ResourceManager.GetString("FindColon", resourceCulture);
            }
        }
        
        public static string FindColonSpace {
            get {
                return ResourceManager.GetString("FindColonSpace", resourceCulture);
            }
        }
        
        public static string UntaggedPhotos {
            get {
                return ResourceManager.GetString("UntaggedPhotos", resourceCulture);
            }
        }
        
        public static string RatedPhotos {
            get {
                return ResourceManager.GetString("RatedPhotos", resourceCulture);
            }
        }
        
        public static string ImportRoll {
            get {
                return ResourceManager.GetString("ImportRoll", resourceCulture);
            }
        }
        
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        public static string RefreshSearch {
            get {
                return ResourceManager.GetString("RefreshSearch", resourceCulture);
            }
        }
        
        public static string NoMatchingPhotosFound {
            get {
                return ResourceManager.GetString("NoMatchingPhotosFound", resourceCulture);
            }
        }
        
        public static string NoPhotosMatchingXFound {
            get {
                return ResourceManager.GetString("NoPhotosMatchingXFound", resourceCulture);
            }
        }
        
        public static string FindWith {
            get {
                return ResourceManager.GetString("FindWith", resourceCulture);
            }
        }
        
        public static string FindWithPlural {
            get {
                return ResourceManager.GetString("FindWithPlural", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string PhotoManagementForGNOME {
            get {
                return ResourceManager.GetString("PhotoManagementForGNOME", resourceCulture);
            }
        }
        
        public static string CopyrightAboutDialog {
            get {
                return ResourceManager.GetString("CopyrightAboutDialog", resourceCulture);
            }
        }
        
        public static string TranslatorCredits {
            get {
                return ResourceManager.GetString("TranslatorCredits", resourceCulture);
            }
        }
        
        public static string FSpotWebsite {
            get {
                return ResourceManager.GetString("FSpotWebsite", resourceCulture);
            }
        }
        
        public static string ShiftAllPhotosByOffset {
            get {
                return ResourceManager.GetString("ShiftAllPhotosByOffset", resourceCulture);
            }
        }
        
        public static string PhotoOutOfPhotos {
            get {
                return ResourceManager.GetString("PhotoOutOfPhotos", resourceCulture);
            }
        }
        
        public static string PhotoPhotoOutOfPhotos {
            get {
                return ResourceManager.GetString("PhotoPhotoOutOfPhotos", resourceCulture);
            }
        }
        
        public static string ThisNameIsAlreadyInUse {
            get {
                return ResourceManager.GetString("ThisNameIsAlreadyInUse", resourceCulture);
            }
        }
        
        public static string CreateNewTag {
            get {
                return ResourceManager.GetString("CreateNewTag", resourceCulture);
            }
        }
        
        public static string NameOfNewTagColon {
            get {
                return ResourceManager.GetString("NameOfNewTagColon", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string Last7days {
            get {
                return ResourceManager.GetString("Last7days", resourceCulture);
            }
        }
        
        public static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        public static string Last90Days {
            get {
                return ResourceManager.GetString("Last90Days", resourceCulture);
            }
        }
        
        public static string Last360Days {
            get {
                return ResourceManager.GetString("Last360Days", resourceCulture);
            }
        }
        
        public static string CurrentWeekMonSun {
            get {
                return ResourceManager.GetString("CurrentWeekMonSun", resourceCulture);
            }
        }
        
        public static string PreviousWeekMonSun {
            get {
                return ResourceManager.GetString("PreviousWeekMonSun", resourceCulture);
            }
        }
        
        public static string AllImages {
            get {
                return ResourceManager.GetString("AllImages", resourceCulture);
            }
        }
        
        public static string CustomizedRange {
            get {
                return ResourceManager.GetString("CustomizedRange", resourceCulture);
            }
        }
        
        public static string ReceivedExceptionXUnableToSavePhotoName {
            get {
                return ResourceManager.GetString("ReceivedExceptionXUnableToSavePhotoName", resourceCulture);
            }
        }
        
        public static string ErrorEditingPhoto {
            get {
                return ResourceManager.GetString("ErrorEditingPhoto", resourceCulture);
            }
        }
        
        public static string EditIconForTagName {
            get {
                return ResourceManager.GetString("EditIconForTagName", resourceCulture);
            }
        }
        
        public static string SelectPhotoFromFile {
            get {
                return ResourceManager.GetString("SelectPhotoFromFile", resourceCulture);
            }
        }
        
        public static string FromPhoto {
            get {
                return ResourceManager.GetString("FromPhoto", resourceCulture);
            }
        }
        
        public static string TagFromPhotoLabelMessage {
            get {
                return ResourceManager.GetString("TagFromPhotoLabelMessage", resourceCulture);
            }
        }
        
        public static string UnableToLoadImage {
            get {
                return ResourceManager.GetString("UnableToLoadImage", resourceCulture);
            }
        }
        
        public static string UnableToLoadPhotoAsIconForTheTag {
            get {
                return ResourceManager.GetString("UnableToLoadPhotoAsIconForTheTag", resourceCulture);
            }
        }
        
        public static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        public static string ChooseImportSource {
            get {
                return ResourceManager.GetString("ChooseImportSource", resourceCulture);
            }
        }
        
        public static string ParenNoCamerasDetectedParen {
            get {
                return ResourceManager.GetString("ParenNoCamerasDetectedParen", resourceCulture);
            }
        }
        
        public static string CheckingThisBoxWillRemoveTheImportedPHotosFromCamera {
            get {
                return ResourceManager.GetString("CheckingThisBoxWillRemoveTheImportedPHotosFromCamera", resourceCulture);
            }
        }
        
        public static string UseThisOptionAtYourOwnRisk {
            get {
                return ResourceManager.GetString("UseThisOptionAtYourOwnRisk", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        public static string ImportingPhotosPhotoOfPhotos {
            get {
                return ResourceManager.GetString("ImportingPhotosPhotoOfPhotos", resourceCulture);
            }
        }
        
        public static string ImportingPhotos {
            get {
                return ResourceManager.GetString("ImportingPhotos", resourceCulture);
            }
        }
        
        public static string SearchingForPhotosYouCanAlreadyClickImportToContinue {
            get {
                return ResourceManager.GetString("SearchingForPhotosYouCanAlreadyClickImportToContinue", resourceCulture);
            }
        }
        
        public static string ImportFailures {
            get {
                return ResourceManager.GetString("ImportFailures", resourceCulture);
            }
        }
        
        public static string SomeFilesFailedToImport {
            get {
                return ResourceManager.GetString("SomeFilesFailedToImport", resourceCulture);
            }
        }
        
        public static string SomeFilesCouldNotBeImportedMightBeCorruptOrWrongWithStorage {
            get {
                return ResourceManager.GetString("SomeFilesCouldNotBeImportedMightBeCorruptOrWrongWithStorage", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string SystemProfile {
            get {
                return ResourceManager.GetString("SystemProfile", resourceCulture);
            }
        }
        
        public static string StandardTheme {
            get {
                return ResourceManager.GetString("StandardTheme", resourceCulture);
            }
        }
        
        public static string ErrorLoadingDatabase {
            get {
                return ResourceManager.GetString("ErrorLoadingDatabase", resourceCulture);
            }
        }
        
        public static string FSpotEncounteredAnErrorWhileLoadingThePhotoDatabase {
            get {
                return ResourceManager.GetString("FSpotEncounteredAnErrorWhileLoadingThePhotoDatabase", resourceCulture);
            }
        }
        
        public static string NewSelection {
            get {
                return ResourceManager.GetString("NewSelection", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        public static string CreateNewVersion {
            get {
                return ResourceManager.GetString("CreateNewVersion", resourceCulture);
            }
        }
        
        public static string RenameVersion {
            get {
                return ResourceManager.GetString("RenameVersion", resourceCulture);
            }
        }
        
        public static string NewNameColon {
            get {
                return ResourceManager.GetString("NewNameColon", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string NoSelectionAvailable {
            get {
                return ResourceManager.GetString("NoSelectionAvailable", resourceCulture);
            }
        }
        
        public static string ThisToolRequiresAnActiveSelection {
            get {
                return ResourceManager.GetString("ThisToolRequiresAnActiveSelection", resourceCulture);
            }
        }
        
        public static string ErrorSavingAdjustedPhoto {
            get {
                return ResourceManager.GetString("ErrorSavingAdjustedPhoto", resourceCulture);
            }
        }
        
        public static string ErrorSavingAdjustedPhotos {
            get {
                return ResourceManager.GetString("ErrorSavingAdjustedPhotos", resourceCulture);
            }
        }
        
        public static string ReceivedExceptionExNoteThatYouHaveToDevelopRawFilesInto {
            get {
                return ResourceManager.GetString("ReceivedExceptionExNoteThatYouHaveToDevelopRawFilesInto", resourceCulture);
            }
        }
        
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        public static string Filesystem {
            get {
                return ResourceManager.GetString("Filesystem", resourceCulture);
            }
        }
        
        public static string ParenUnknownParen {
            get {
                return ResourceManager.GetString("ParenUnknownParen", resourceCulture);
            }
        }
        
        public static string ImageInformation {
            get {
                return ResourceManager.GetString("ImageInformation", resourceCulture);
            }
        }
        
        public static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string NumberPhoto {
            get {
                return ResourceManager.GetString("NumberPhoto", resourceCulture);
            }
        }
        
        public static string NumberPhotos {
            get {
                return ResourceManager.GetString("NumberPhotos", resourceCulture);
            }
        }
        
        public static string ParenNoEditsParen {
            get {
                return ResourceManager.GetString("ParenNoEditsParen", resourceCulture);
            }
        }
        
        public static string ParenOneEditParen {
            get {
                return ResourceManager.GetString("ParenOneEditParen", resourceCulture);
            }
        }
        
        public static string ParenXEditsParen {
            get {
                return ResourceManager.GetString("ParenXEditsParen", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string ShowDate {
            get {
                return ResourceManager.GetString("ShowDate", resourceCulture);
            }
        }
        
        public static string OnDateBetweenTimeAndTime {
            get {
                return ResourceManager.GetString("OnDateBetweenTimeAndTime", resourceCulture);
            }
        }
        
        public static string BetweenTimeAndTime {
            get {
                return ResourceManager.GetString("BetweenTimeAndTime", resourceCulture);
            }
        }
        
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        public static string ShowSize {
            get {
                return ResourceManager.GetString("ShowSize", resourceCulture);
            }
        }
        
        public static string Exposure {
            get {
                return ResourceManager.GetString("Exposure", resourceCulture);
            }
        }
        
        public static string ShowExposure {
            get {
                return ResourceManager.GetString("ShowExposure", resourceCulture);
            }
        }
        
        public static string FlashFired {
            get {
                return ResourceManager.GetString("FlashFired", resourceCulture);
            }
        }
        
        public static string FlashDidntFire {
            get {
                return ResourceManager.GetString("FlashDidntFire", resourceCulture);
            }
        }
        
        public static string FocalLength {
            get {
                return ResourceManager.GetString("FocalLength", resourceCulture);
            }
        }
        
        public static string ShowFocalLength {
            get {
                return ResourceManager.GetString("ShowFocalLength", resourceCulture);
            }
        }
        
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        public static string ShowCamera {
            get {
                return ResourceManager.GetString("ShowCamera", resourceCulture);
            }
        }
        
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        public static string ShowCreator {
            get {
                return ResourceManager.GetString("ShowCreator", resourceCulture);
            }
        }
        
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        public static string ShowFileSize {
            get {
                return ResourceManager.GetString("ShowFileSize", resourceCulture);
            }
        }
        
        public static string ParenFileReadErrorParen {
            get {
                return ResourceManager.GetString("ParenFileReadErrorParen", resourceCulture);
            }
        }
        
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        public static string ShowRating {
            get {
                return ResourceManager.GetString("ShowRating", resourceCulture);
            }
        }
        
        public static string ShowTags {
            get {
                return ResourceManager.GetString("ShowTags", resourceCulture);
            }
        }
        
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        public static string ExtendedMetadata {
            get {
                return ResourceManager.GetString("ExtendedMetadata", resourceCulture);
            }
        }
        
        public static string NoActivePhoto {
            get {
                return ResourceManager.GetString("NoActivePhoto", resourceCulture);
            }
        }
        
        public static string ThePhotoXDoesNotExist {
            get {
                return ResourceManager.GetString("ThePhotoXDoesNotExist", resourceCulture);
            }
        }
        
        public static string NoMetadataAvailable {
            get {
                return ResourceManager.GetString("NoMetadataAvailable", resourceCulture);
            }
        }
        
        public static string DeleteTheSelectedPhotoPermanent {
            get {
                return ResourceManager.GetString("DeleteTheSelectedPhotoPermanent", resourceCulture);
            }
        }
        
        public static string DeleteTheXSelectedPhotosPermanent {
            get {
                return ResourceManager.GetString("DeleteTheXSelectedPhotosPermanent", resourceCulture);
            }
        }
        
        public static string ThisDeletesAllVersionsOfTheSelectedPhotoFromYourDrive {
            get {
                return ResourceManager.GetString("ThisDeletesAllVersionsOfTheSelectedPhotoFromYourDrive", resourceCulture);
            }
        }
        
        public static string ThisDeletesAllVersionsOfTheSelectedPhotosFromYourDrive {
            get {
                return ResourceManager.GetString("ThisDeletesAllVersionsOfTheSelectedPhotosFromYourDrive", resourceCulture);
            }
        }
        
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        public static string DeletePhotos {
            get {
                return ResourceManager.GetString("DeletePhotos", resourceCulture);
            }
        }
        
        public static string RemoveTheSelectedPhotoFromFSpot {
            get {
                return ResourceManager.GetString("RemoveTheSelectedPhotoFromFSpot", resourceCulture);
            }
        }
        
        public static string RemoveTheXSelectedPhotosFromFSpot {
            get {
                return ResourceManager.GetString("RemoveTheXSelectedPhotosFromFSpot", resourceCulture);
            }
        }
        
        public static string IfYouRemovePhotosFromTheFSpotCatalogAllTagInformationWillBeLost {
            get {
                return ResourceManager.GetString("IfYouRemovePhotosFromTheFSpotCatalogAllTagInformationWillBeLost", resourceCulture);
            }
        }
        
        public static string RemoveFromCatalog {
            get {
                return ResourceManager.GetString("RemoveFromCatalog", resourceCulture);
            }
        }
        
        public static string DeleteTagXQuestion {
            get {
                return ResourceManager.GetString("DeleteTagXQuestion", resourceCulture);
            }
        }
        
        public static string DeleteTheXSelectedTagsQuestion {
            get {
                return ResourceManager.GetString("DeleteTheXSelectedTagsQuestion", resourceCulture);
            }
        }
        
        public static string IfYouDeleteThisTagTheAssociationWithXYWillBeLost {
            get {
                return ResourceManager.GetString("IfYouDeleteThisTagTheAssociationWithXYWillBeLost", resourceCulture);
            }
        }
        
        public static string IfYouDeleteThisTagsTheAssociationWithXYWillBeLost {
            get {
                return ResourceManager.GetString("IfYouDeleteThisTagsTheAssociationWithXYWillBeLost", resourceCulture);
            }
        }
        
        public static string DeleteTagModifier {
            get {
                return ResourceManager.GetString("DeleteTagModifier", resourceCulture);
            }
        }
        
        public static string DeleteTagsModifier {
            get {
                return ResourceManager.GetString("DeleteTagsModifier", resourceCulture);
            }
        }
        
        public static string TagIsNotEmpty {
            get {
                return ResourceManager.GetString("TagIsNotEmpty", resourceCulture);
            }
        }
        
        public static string CanNotDeleteTagsThatHaveTagsWithinThemPleaseDeleteTagsUnderXFirst {
            get {
                return ResourceManager.GetString("CanNotDeleteTagsThatHaveTagsWithinThemPleaseDeleteTagsUnderXFirst", resourceCulture);
            }
        }
        
        public static string RotateSelectedPhotoLeft {
            get {
                return ResourceManager.GetString("RotateSelectedPhotoLeft", resourceCulture);
            }
        }
        
        public static string RotateSelectedPhotosLeft {
            get {
                return ResourceManager.GetString("RotateSelectedPhotosLeft", resourceCulture);
            }
        }
        
        public static string RotateSelectedPhotoRight {
            get {
                return ResourceManager.GetString("RotateSelectedPhotoRight", resourceCulture);
            }
        }
        
        public static string RotateSelectedPhotosRight {
            get {
                return ResourceManager.GetString("RotateSelectedPhotosRight", resourceCulture);
            }
        }
        
        public static string FindSelectedTag {
            get {
                return ResourceManager.GetString("FindSelectedTag", resourceCulture);
            }
        }
        
        public static string FindSelectedTags {
            get {
                return ResourceManager.GetString("FindSelectedTags", resourceCulture);
            }
        }
        
        public static string FindSelectedTagWith {
            get {
                return ResourceManager.GetString("FindSelectedTagWith", resourceCulture);
            }
        }
        
        public static string FindSelectedTagsWith {
            get {
                return ResourceManager.GetString("FindSelectedTagsWith", resourceCulture);
            }
        }
        
        public static string CreateNewVersionQuestion {
            get {
                return ResourceManager.GetString("CreateNewVersionQuestion", resourceCulture);
            }
        }
        
        public static string CreateNewVersionsQuestion {
            get {
                return ResourceManager.GetString("CreateNewVersionsQuestion", resourceCulture);
            }
        }
        
        public static string BeforeLaunchingXShouldFSpotCreateANewVersionOfTheSelectedPhotoToPreserveTheOriginialQ {
            get {
                return ResourceManager.GetString("BeforeLaunchingXShouldFSpotCreateANewVersionOfTheSelectedPhotoToPreserveTheOrigin" +
                        "ialQ", resourceCulture);
            }
        }
        
        public static string BeforeLaunchingXShouldFSpotCreateANewVersionsOfTheSelectedPhotoToPreserveTheOriginialQ {
            get {
                return ResourceManager.GetString("BeforeLaunchingXShouldFSpotCreateANewVersionsOfTheSelectedPhotoToPreserveTheOrigi" +
                        "nialQ", resourceCulture);
            }
        }
        
        public static string ErrorSavingSharpenedPhoto {
            get {
                return ResourceManager.GetString("ErrorSavingSharpenedPhoto", resourceCulture);
            }
        }
        
        public static string SharpeningCompleteExclamation {
            get {
                return ResourceManager.GetString("SharpeningCompleteExclamation", resourceCulture);
            }
        }
        
        public static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        public static string AmountColon {
            get {
                return ResourceManager.GetString("AmountColon", resourceCulture);
            }
        }
        
        public static string RadiusColon {
            get {
                return ResourceManager.GetString("RadiusColon", resourceCulture);
            }
        }
        
        public static string ThresholdColon {
            get {
                return ResourceManager.GetString("ThresholdColon", resourceCulture);
            }
        }
        
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        public static string TheTagXIsNotAppliedToAnyPhotosLongMsg {
            get {
                return ResourceManager.GetString("TheTagXIsNotAppliedToAnyPhotosLongMsg", resourceCulture);
            }
        }
        
        public static string SearchReturnedNoResults {
            get {
                return ResourceManager.GetString("SearchReturnedNoResults", resourceCulture);
            }
        }
        
        public static string TheTagFSpotIsLookingForDoesNotExistTryLongMsg {
            get {
                return ResourceManager.GetString("TheTagFSpotIsLookingForDoesNotExistTryLongMsg", resourceCulture);
            }
        }
        
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        public static string HideToolbar {
            get {
                return ResourceManager.GetString("HideToolbar", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        public static string ExitFullscreen {
            get {
                return ResourceManager.GetString("ExitFullscreen", resourceCulture);
            }
        }
        
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        public static string StartSlideshow {
            get {
                return ResourceManager.GetString("StartSlideshow", resourceCulture);
            }
        }
        
        public static string SlideTransitionColon {
            get {
                return ResourceManager.GetString("SlideTransitionColon", resourceCulture);
            }
        }
        
        public static string MoreDates {
            get {
                return ResourceManager.GetString("MoreDates", resourceCulture);
            }
        }
        
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        public static string ClearDateRange {
            get {
                return ResourceManager.GetString("ClearDateRange", resourceCulture);
            }
        }
        
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        public static string RotateLeftMenuItem {
            get {
                return ResourceManager.GetString("RotateLeftMenuItem", resourceCulture);
            }
        }
        
        public static string RotatePictureLeft {
            get {
                return ResourceManager.GetString("RotatePictureLeft", resourceCulture);
            }
        }
        
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        public static string RotateRightMenuItem {
            get {
                return ResourceManager.GetString("RotateRightMenuItem", resourceCulture);
            }
        }
        
        public static string RotatePictureRight {
            get {
                return ResourceManager.GetString("RotatePictureRight", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string NextPicture {
            get {
                return ResourceManager.GetString("NextPicture", resourceCulture);
            }
        }
        
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        public static string PreviousPicture {
            get {
                return ResourceManager.GetString("PreviousPicture", resourceCulture);
            }
        }
        
        public static string ImportPhotosEllipsis {
            get {
                return ResourceManager.GetString("ImportPhotosEllipsis", resourceCulture);
            }
        }
        
        public static string ImportNewPhotos {
            get {
                return ResourceManager.GetString("ImportNewPhotos", resourceCulture);
            }
        }
        
        public static string Browsing {
            get {
                return ResourceManager.GetString("Browsing", resourceCulture);
            }
        }
        
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        public static string EditYourPhotos {
            get {
                return ResourceManager.GetString("EditYourPhotos", resourceCulture);
            }
        }
        
        public static string ViewPhotosFullscrenn {
            get {
                return ResourceManager.GetString("ViewPhotosFullscrenn", resourceCulture);
            }
        }
        
        public static string PreviousPhoto {
            get {
                return ResourceManager.GetString("PreviousPhoto", resourceCulture);
            }
        }
        
        public static string NextPhoto {
            get {
                return ResourceManager.GetString("NextPhoto", resourceCulture);
            }
        }
        
        public static string ShowFindBar {
            get {
                return ResourceManager.GetString("ShowFindBar", resourceCulture);
            }
        }
        
        public static string HideFindBar {
            get {
                return ResourceManager.GetString("HideFindBar", resourceCulture);
            }
        }
        
        public static string BrowseYourPhotoLibrary {
            get {
                return ResourceManager.GetString("BrowseYourPhotoLibrary", resourceCulture);
            }
        }
        
        public static string ThisOperationWillMergeTheSelectedTagsAndAnySubTagsIntoASingleTag {
            get {
                return ResourceManager.GetString("ThisOperationWillMergeTheSelectedTagsAndAnySubTagsIntoASingleTag", resourceCulture);
            }
        }
        
        public static string MergeTagsModifier {
            get {
                return ResourceManager.GetString("MergeTagsModifier", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string ErrorDeletingPicture {
            get {
                return ResourceManager.GetString("ErrorDeletingPicture", resourceCulture);
            }
        }
        
        public static string NoPermissionToDeleteTheFileColon {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteTheFileColon", resourceCulture);
            }
        }
        
        public static string AnErrorOfTypeXOccurredWhileDeletingTheFile {
            get {
                return ResourceManager.GetString("AnErrorOfTypeXOccurredWhileDeletingTheFile", resourceCulture);
            }
        }
        
        public static string XCFVersion {
            get {
                return ResourceManager.GetString("XCFVersion", resourceCulture);
            }
        }
        
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        public static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        public static string UnableToRotateThisTypeOfPhoto {
            get {
                return ResourceManager.GetString("UnableToRotateThisTypeOfPhoto", resourceCulture);
            }
        }
        
        public static string UnableToRotateReadonlyFile {
            get {
                return ResourceManager.GetString("UnableToRotateReadonlyFile", resourceCulture);
            }
        }
        
        public static string RotatingPhotos {
            get {
                return ResourceManager.GetString("RotatingPhotos", resourceCulture);
            }
        }
        
        public static string RotatingPhotoX {
            get {
                return ResourceManager.GetString("RotatingPhotoX", resourceCulture);
            }
        }
        
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        public static string UnableToRotatePhoto {
            get {
                return ResourceManager.GetString("UnableToRotatePhoto", resourceCulture);
            }
        }
        
        public static string UnableToRotateXPhotos {
            get {
                return ResourceManager.GetString("UnableToRotateXPhotos", resourceCulture);
            }
        }
        
        public static string ThePhotoCouldNotBeRotatedBecauseItIsOnAReadonlyFileSystemOrMedia {
            get {
                return ResourceManager.GetString("ThePhotoCouldNotBeRotatedBecauseItIsOnAReadonlyFileSystemOrMedia", resourceCulture);
            }
        }
        
        public static string XPhotosCouldNotBeRotatedBecauseItIsOnAReadonlyFileSystemOrMedia {
            get {
                return ResourceManager.GetString("XPhotosCouldNotBeRotatedBecauseItIsOnAReadonlyFileSystemOrMedia", resourceCulture);
            }
        }
        
        public static string ReceivedErrorXWhileAttemptingToRotateY {
            get {
                return ResourceManager.GetString("ReceivedErrorXWhileAttemptingToRotateY", resourceCulture);
            }
        }
        
        public static string ErrorWhileRotatingPhoto {
            get {
                return ResourceManager.GetString("ErrorWhileRotatingPhoto", resourceCulture);
            }
        }
        
        public static string PreparingEmail {
            get {
                return ResourceManager.GetString("PreparingEmail", resourceCulture);
            }
        }
        
        public static string ExportingPictureX {
            get {
                return ResourceManager.GetString("ExportingPictureX", resourceCulture);
            }
        }
        
        public static string ErrorPreparingXColonSpaceY {
            get {
                return ResourceManager.GetString("ErrorPreparingXColonSpaceY", resourceCulture);
            }
        }
        
        public static string ErrorProcessingImage {
            get {
                return ResourceManager.GetString("ErrorProcessingImage", resourceCulture);
            }
        }
        
        public static string AnErrorOccurredWhileProcessingSpaceXColonSpaceY {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileProcessingSpaceXColonSpaceY", resourceCulture);
            }
        }
        
        public static string MyPhotos {
            get {
                return ResourceManager.GetString("MyPhotos", resourceCulture);
            }
        }
        
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        public static string RotatePhotoLeft {
            get {
                return ResourceManager.GetString("RotatePhotoLeft", resourceCulture);
            }
        }
        
        public static string RotatePhotoRight {
            get {
                return ResourceManager.GetString("RotatePhotoRight", resourceCulture);
            }
        }
        
        public static string ViewPhotosFullscreen {
            get {
                return ResourceManager.GetString("ViewPhotosFullscreen", resourceCulture);
            }
        }
        
        public static string ViewPhotosInASlideshow {
            get {
                return ResourceManager.GetString("ViewPhotosInASlideshow", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        public static string SetAsBackground {
            get {
                return ResourceManager.GetString("SetAsBackground", resourceCulture);
            }
        }
        
        public static string ErrorRenamingTag {
            get {
                return ResourceManager.GetString("ErrorRenamingTag", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string ReallyDeleteVersionXQuestion {
            get {
                return ResourceManager.GetString("ReallyDeleteVersionXQuestion", resourceCulture);
            }
        }
        
        public static string ThisRemovesTheVersionAndDeletesTheCorrespondingFileFromDisk {
            get {
                return ResourceManager.GetString("ThisRemovesTheVersionAndDeletesTheCorrespondingFileFromDisk", resourceCulture);
            }
        }
        
        public static string DetachButton {
            get {
                return ResourceManager.GetString("DetachButton", resourceCulture);
            }
        }
        
        public static string ReallyDetachVersionXFromYQuestion {
            get {
                return ResourceManager.GetString("ReallyDetachVersionXFromYQuestion", resourceCulture);
            }
        }
        
        public static string ThisMakesTheVersionAppearAsASeperatePhotoInTheLibraryToUndoDragTheNewPhotoBackToItsParent {
            get {
                return ResourceManager.GetString("ThisMakesTheVersionAppearAsASeperatePhotoInTheLibraryToUndoDragTheNewPhotoBackToI" +
                        "tsParent", resourceCulture);
            }
        }
        
        public static string ReparentButton {
            get {
                return ResourceManager.GetString("ReparentButton", resourceCulture);
            }
        }
        
        public static string ReallyReparentXAsVersionOfYQuestion {
            get {
                return ResourceManager.GetString("ReallyReparentXAsVersionOfYQuestion", resourceCulture);
            }
        }
        
        public static string ReallyReparentXPhotosAsVersionOfYQuestion {
            get {
                return ResourceManager.GetString("ReallyReparentXPhotosAsVersionOfYQuestion", resourceCulture);
            }
        }
        
        public static string ThisMakesThePhotosAppearAsASingleOneInTheLibraryTheVersionsCanBeDetachedUsingThePhotoMenu {
            get {
                return ResourceManager.GetString("ThisMakesThePhotosAppearAsASingleOneInTheLibraryTheVersionsCanBeDetachedUsingTheP" +
                        "hotoMenu", resourceCulture);
            }
        }
        
        public static string ReceivedExceptionX {
            get {
                return ResourceManager.GetString("ReceivedExceptionX", resourceCulture);
            }
        }
        
        public static string CreateNewTagEllipsis {
            get {
                return ResourceManager.GetString("CreateNewTagEllipsis", resourceCulture);
            }
        }
        
        public static string EditTagEllipsis {
            get {
                return ResourceManager.GetString("EditTagEllipsis", resourceCulture);
            }
        }
        
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        public static string DeleteTags {
            get {
                return ResourceManager.GetString("DeleteTags", resourceCulture);
            }
        }
        
        public static string AttachTagToSelection {
            get {
                return ResourceManager.GetString("AttachTagToSelection", resourceCulture);
            }
        }
        
        public static string AttachTagsToSelection {
            get {
                return ResourceManager.GetString("AttachTagsToSelection", resourceCulture);
            }
        }
        
        public static string RemoveTagToSelection {
            get {
                return ResourceManager.GetString("RemoveTagToSelection", resourceCulture);
            }
        }
        
        public static string RemoveTagsToSelection {
            get {
                return ResourceManager.GetString("RemoveTagsToSelection", resourceCulture);
            }
        }
        
        public static string MergeTags {
            get {
                return ResourceManager.GetString("MergeTags", resourceCulture);
            }
        }
        
        public static string PhotoIsBeingSharpened {
            get {
                return ResourceManager.GetString("PhotoIsBeingSharpened", resourceCulture);
            }
        }
        
        public static string MergeTheSelectedTagQuestion {
            get {
                return ResourceManager.GetString("MergeTheSelectedTagQuestion", resourceCulture);
            }
        }
        
        public static string MergeTheXSelectedTagsQuestion {
            get {
                return ResourceManager.GetString("MergeTheXSelectedTagsQuestion", resourceCulture);
            }
        }
        
        public static string XPhotoOutOfY {
            get {
                return ResourceManager.GetString("XPhotoOutOfY", resourceCulture);
            }
        }
        
        public static string XPhotosOutOfY {
            get {
                return ResourceManager.GetString("XPhotosOutOfY", resourceCulture);
            }
        }
        
        public static string XPhoto {
            get {
                return ResourceManager.GetString("XPhoto", resourceCulture);
            }
        }
        
        public static string XPhotos {
            get {
                return ResourceManager.GetString("XPhotos", resourceCulture);
            }
        }
        
        public static string ParenXSelectedParen {
            get {
                return ResourceManager.GetString("ParenXSelectedParen", resourceCulture);
            }
        }
    }
}
